xdog:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint13_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_13
    pid: {p: 5000.0, i: 0.0, d: 100.0}
  joint12_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_12
    pid: {p: 5000.0, i: 0.0, d: 100.0}
  joint11_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_11
    pid: {p: 5000.0, i: 0.0, d: 100.0}
  joint23_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_23
    pid: {p: 5000.0, i: 0.0, d: 100.0}
  joint22_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_22
    pid: {p: 5000.0, i: 0.0, d: 100.0}
  joint21_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_21
    pid: {p: 5000.0, i: 0.0, d: 100.0}
  joint33_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_33
    pid: {p: 5000.0, i: 0.0, d: 100.0}
  joint32_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_32
    pid: {p: 5000.0, i: 0.0, d: 100.0}
  joint31_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_31
    pid: {p: 5000.0, i: 0.0, d: 100.0}
  joint43_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_43
    pid: {p: 5000.0, i: 0.0, d: 100.0}
  joint42_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_42
    pid: {p: 5000.0, i: 0.0, d: 100.0}
  joint41_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint_41
    pid: {p: 5000.0, i: 0.0, d: 100.0}

#gazebo_ros_control/pid_gains:
  #Joint_13: {p: 5000.0, i: 0.0, d: 100.0}
  #Joint_12: {p: 5000.0, i: 0.0, d: 100.0}
  #Joint_11: {p: 5000.0, i: 0.0, d: 100.0}
  #Joint_23: {p: 5000.0, i: 0.0, d: 100.0}
  #Joint_22: {p: 5000.0, i: 0.0, d: 100.0}
  #Joint_21: {p: 5000.0, i: 0.0, d: 100.0}
  #Joint_33: {p: 5000.0, i: 0.0, d: 100.0}
  #Joint_32: {p: 5000.0, i: 0.0, d: 100.0}
  #Joint_31: {p: 5000.0, i: 0.0, d: 100.0}
  #Joint_43: {p: 5000.0, i: 0.0, d: 100.0}
  #Joint_42: {p: 5000.0, i: 0.0, d: 100.0}
  #Joint_41: {p: 5000.0, i: 0.0, d: 100.0}

